trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd src/IO.Swagger
    docker build -t io.swagger .
  displayName: 'Build Docker Image'

- script: |
    docker run -d -p 5000:5000 io.swagger
  displayName: 'Run Docker Container'
