# Nome do pipeline
name: Build and Run Docker Image

# Evento que dispara o pipeline - neste caso, um push para a branch principal
on:
  push:
    branches:
      - main
jobs:
  build_and_run:
    # Especificar o tipo de runner (máquina) que você deseja usar
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      # Fazer checkout do seu código para o runner
      uses: actions/checkout@v2

    - name: Build Docker Image
      # Construir a imagem Docker
      run: |
        cd src/IO.Swagger
        docker build -t io.swagger .

    - name: Run Docker Container
      # Executar a imagem Docker como um container
      run: |
        docker run -d -p 5000:5000 io.swagger

    # Adicionar mais passos conforme necessário, por exemplo, para testes ou deploy
