/*
 * myLIMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class WorkInfo : IEquatable<WorkInfo>
    { 
        /// <summary>
        /// Gets or Sets InfoId
        /// </summary>

        [DataMember(Name="InfoId")]
        public int? InfoId { get; set; }

        /// <summary>
        /// Gets or Sets Identification
        /// </summary>

        [DataMember(Name="Identification")]
        public string Identification { get; set; }

        /// <summary>
        /// Gets or Sets DisplayValue
        /// </summary>

        [DataMember(Name="DisplayValue")]
        public string DisplayValue { get; set; }

        /// <summary>
        /// Gets or Sets NumericValue
        /// </summary>

        [DataMember(Name="NumericValue")]
        public float? NumericValue { get; set; }

        /// <summary>
        /// Gets or Sets MeasurementUnitId
        /// </summary>

        [DataMember(Name="MeasurementUnitId")]
        public int? MeasurementUnitId { get; set; }

        /// <summary>
        /// Gets or Sets MeasurementUnitIdentification
        /// </summary>

        [DataMember(Name="MeasurementUnitIdentification")]
        public string MeasurementUnitIdentification { get; set; }

        /// <summary>
        /// Gets or Sets EquivalencyId
        /// </summary>

        [DataMember(Name="EquivalencyId")]
        public int? EquivalencyId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WorkInfo {\n");
            sb.Append("  InfoId: ").Append(InfoId).Append("\n");
            sb.Append("  Identification: ").Append(Identification).Append("\n");
            sb.Append("  DisplayValue: ").Append(DisplayValue).Append("\n");
            sb.Append("  NumericValue: ").Append(NumericValue).Append("\n");
            sb.Append("  MeasurementUnitId: ").Append(MeasurementUnitId).Append("\n");
            sb.Append("  MeasurementUnitIdentification: ").Append(MeasurementUnitIdentification).Append("\n");
            sb.Append("  EquivalencyId: ").Append(EquivalencyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((WorkInfo)obj);
        }

        /// <summary>
        /// Returns true if WorkInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of WorkInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkInfo other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    InfoId == other.InfoId ||
                    InfoId != null &&
                    InfoId.Equals(other.InfoId)
                ) && 
                (
                    Identification == other.Identification ||
                    Identification != null &&
                    Identification.Equals(other.Identification)
                ) && 
                (
                    DisplayValue == other.DisplayValue ||
                    DisplayValue != null &&
                    DisplayValue.Equals(other.DisplayValue)
                ) && 
                (
                    NumericValue == other.NumericValue ||
                    NumericValue != null &&
                    NumericValue.Equals(other.NumericValue)
                ) && 
                (
                    MeasurementUnitId == other.MeasurementUnitId ||
                    MeasurementUnitId != null &&
                    MeasurementUnitId.Equals(other.MeasurementUnitId)
                ) && 
                (
                    MeasurementUnitIdentification == other.MeasurementUnitIdentification ||
                    MeasurementUnitIdentification != null &&
                    MeasurementUnitIdentification.Equals(other.MeasurementUnitIdentification)
                ) && 
                (
                    EquivalencyId == other.EquivalencyId ||
                    EquivalencyId != null &&
                    EquivalencyId.Equals(other.EquivalencyId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (InfoId != null)
                    hashCode = hashCode * 59 + InfoId.GetHashCode();
                    if (Identification != null)
                    hashCode = hashCode * 59 + Identification.GetHashCode();
                    if (DisplayValue != null)
                    hashCode = hashCode * 59 + DisplayValue.GetHashCode();
                    if (NumericValue != null)
                    hashCode = hashCode * 59 + NumericValue.GetHashCode();
                    if (MeasurementUnitId != null)
                    hashCode = hashCode * 59 + MeasurementUnitId.GetHashCode();
                    if (MeasurementUnitIdentification != null)
                    hashCode = hashCode * 59 + MeasurementUnitIdentification.GetHashCode();
                    if (EquivalencyId != null)
                    hashCode = hashCode * 59 + EquivalencyId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(WorkInfo left, WorkInfo right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(WorkInfo left, WorkInfo right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
